apiVersion: apps/v1
{{- if .Values.stateful }}
kind: StatefulSet
{{- else }}
kind: Deployment
{{- end }}
metadata:
  name: {{ include "pichart.fullname" . }}
  labels: 
    {{- include "pichart.labels" . | nindent 4 }}
spec:
  {{- if .Values.stateful }}
  {{- range $x := .Values.volumes }}
  {{- if $x.persistentVolumeClaim }}
  {{- $obj := include "pichart.findNameInArray" (dict "array" $.Values.persistentVolumeClaimData "keyword" $x.name) | fromYaml }}
  volumeClaimTemplates:
  - metadata:
      name: {{ $x.persistentVolumeClaim.claimName }}
      labels:
        {{- include "pichart.labels" $ | nindent 8 }}
      annotations:
        {{- toYaml $obj.annotations | nindent 8 }}
    spec:
      accessModes:
      - {{ $obj.accessmode | default "ReadWriteOnce"  }}
      storageClassName: local-path
      resources:
        requests:
          storage: {{ $obj.request | default "1Gi" }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- if hasKey .Values "revisionHistoryLimit" }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- else }}
  revisionHistoryLimit: 1
  {{- end }}
  {{- if .Values.rollingUpdate }}
  {{- with .Values.rollingUpdate }}
  strategy: 
    rollingUpdate:
      maxSurge: {{ .maxSurge | default 1 }}
      maxUnavailable: {{ .maxSurge | default 1 }}
  {{- end }}
  {{- else if not .Values.stateful }}
  strategy: 
    type: Recreate
  {{- end }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  {{- with .Values.progressDeadlineSeconds }}
  progressDeadlineSeconds: {{ . }}
  {{- end }}
  selector:
    matchLabels: 
      {{- include "pichart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 6 }}
      {{- end }}
      labels:
        {{- include "pichart.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ . }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 6 }}
      {{- end }}
      serviceAccountName: {{ include "pichart.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.initContainers }}
      initContainers: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostNetwork }}
      hostNetwork: {{ . }}
      {{- end }}
      {{- with .Values.dnsPolicy }}
      dnsPolicy: {{ . }}
      {{- end }}
      containers:
      - name: {{ include "pichart.fullname" . }}
        {{- with .Values.securityContext }}
        securityContext: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        {{- range $i := .Values.service.ports }}
        - containerPort: {{ $i.targetPort | default $i.port }}
        {{- end }}
        {{- with .Values.env }}
        env: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.args }}
        args: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.cmd }}
        command: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.livenessProbe }}
        livenessProbe: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.readinessProbe }}
        readinessProbe: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.resources }}
        resources: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.volumeMounts }}
        volumeMounts: 
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- range $k, $v := .Values.sidecars }}
      - name: {{ $k }}
        image: {{ $v.image }}:{{ $v.tag }}
        {{- $map := dict "securityContext" $.Values.securityContext }}
        {{- merge $v.params $map  | toYaml | nindent 8 }}
      {{- end }}
      {{- with .Values.volumes }}
      volumes: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations: 
        {{- toYaml . | nindent 8 }}
      {{- end }}
