apiVersion: v1
kind: ConfigMap
metadata:
  name: public-ip
  namespace: cert-manager
  labels:
    app.kubernetes.io/component: porkbun
    app.kubernetes.io/part-of: porkbun
    app.kubernetes.io/managed-by: kustomize
data:
  ip: 127.0.0.1
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: public-ip-cm-access
  namespace: cert-manager
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["public-ip"]
  verbs: ["get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: public-ip-cm-access-binding
  namespace: cert-manager
subjects:
- kind: ServiceAccount
  name: porkbun
  namespace: cert-manager
roleRef:
  kind: Role
  name: public-ip-cm-access
  apiGroup: rbac.authorization.k8s.io
